CREATE TABLE registrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_type VARCHAR(255),
    schedule VARCHAR(255),
    type_of_registration VARCHAR(255),
    company_name VARCHAR(255),
    Company_uen_reg_no VARCHAR(255),
    contact_person_name VARCHAR(255),
    contact_person_email VARCHAR(255),
    contact_person_phone VARCHAR(255),
    participant_name VARCHAR(255),
    nric_no VARCHAR(255),
    dob DATE,
    gender VARCHAR(50),
    nationality VARCHAR(100),
    race VARCHAR(100),
    contact VARCHAR(50),
    email VARCHAR(100),
    experience TEXT,
    salary_range VARCHAR(50),
    qualification VARCHAR(255),
    certificate_path VARCHAR(255),
    photo_path VARCHAR(255),
    signature TEXT
);
